### PR TITLE
Add library project

### PR DESCRIPTION
**Pull request by Brett208**
Will likely break Linux builds due to new project structure

### CODE REVIEW

**Comment by DanRStevens** [comment]
Hmm, you know if we use end-to-end testing, we won't really need to make this split.

**Comment by Brett208** [comment]
I know this is over-engineering the solution. I am kicking around writing a more robust command line flag parser using templates which might benefit from actual unit tests...

**Comment by DanRStevens** [comment]
Yeah, I kind of figured. It seems like you've wanted to write a command line flag processing library for a while now.

**Comment by DanRStevens** [comment]
This project uses an older style of `makefile`. There's a lot more copy/paste and fixup to get new projects working. I may need to look at this when I'm a little more alert if this is the path we're taking.

**Comment by Brett208** [comment]
Starting to agree with @DanRStevens that a library project may be a bit heavier solution than needed here.

**Pull request closed without merging**
